<?php

/**
 * sfGuardUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    chia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6698 2009-11-10 17:58:02Z jwage $
 */
class sfGuardUserGroup extends PluginsfGuardUserGroup
{
}
